name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout External Repository Branch
        uses: actions/checkout@v3
        with:
          repository: abystoma/external-workflow
          ref: branch
          # If the external repository is private, you may need to provide a token:
          # token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Greetings
        run: echo "$(<greetings.txt)"
